server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
spring:
  application:
    name: consumer-service

user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true

ribbon: #ribbon的超时时长配置
  ConnectionTimeout: 500
  ReadTimeout: 2000
hystrix:  #全局配置，在controller里面就只是局部的
  command:
    default:  #在这里填写方法也可以实现局部，那就不用写这么长的注解了
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000