server:
  port: 10010

#routes:
  #    user-service: /user/**
  #  ignored-services:
#zuul默认为每个在ereka上的服务创建了和服务名相同的映射
#可以通过以下方案修改简单的映射和屏蔽默认服务
zuul:
  routes:
    user-service:
      path: /user/**
      serviceId: user-service
      strip-prefix: false

  ignored-services:
    - consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

spring:
  application:
    name: gateway

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000 # 熔断超时时长：6000ms

ribbon:
  ConnectionTimeOut: 500
  ReadTimeOut: 1000