server:
  port: 8081
spring:
  application:
    name: item-server
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka